# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161229_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text',
            field=models.TextField(default='', verbose_name='Текст статьи'),
        ),
    ]
