# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
