# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170109_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_text',
            field=models.TextField(default='', verbose_name='Аннотация статьи'),
        ),
    ]
